######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 3 07:03:15 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ui
INCLUDEPATH += . ui
LIBS += -lQtNetwork
CONFIG += debug

# Input
HEADERS += ui/rxUDP.h ui/js_code/joystick.h
FORMS += ui/rxUDPGUI.ui
SOURCES += rxUDP_main.cpp ui/rxUDP.cpp ui/js_code/joystick.c
