######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 3 07:03:15 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ui
INCLUDEPATH += . ui
LIBS += -lQtNetwork
CONFIG += debug

# Input
HEADERS += ui/test.h
FORMS += ui/testGUI.ui
SOURCES += test_main.cpp ui/test.cpp
