###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

TARGET	= spi

COMMON_OBJS = spi.o Delay.o Timer.o UART.o Hardware.o

include ../Rules.mk

