######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 3 07:03:15 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ui
INCLUDEPATH += . ui
LIBS += -lQtNetwork
CONFIG += debug

# Input
HEADERS += ui/groundstationform.h ui/driver/joystick.h
FORMS += ui/ahnsabout.ui ui/basegroundstation.ui
SOURCES += ground_main.cpp ui/groundstationform.cpp ui/driver/joystick.c
